apiVersion: v1
kind: Service
metadata:
  name: forgejo-service
spec:
  type: LoadBalancer
  selector:
    app: forgejo
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      # Mapping port 222 on Pi's IP directly to port 22 inside the Forgejo container
    - name: ssh
      port: 222
      targetPort: 22
