apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-pvc
  labels:
    app: forgejo
    environment: pi5
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
